#!/usr/bin/env bash
#
# Generate infra/ansible/inventory/hosts.yml from the Terraform outputs.
# The result is gitignored (IPs change every apply) — regenerate after each `terraform apply`.
#
# Requires: terraform, jq. Run from infra/ansible/:
#   ./inventory/generate-inventory.sh
#
set -euo pipefail

TF_DIR="${TF_DIR:-../terraform/root}"
OUT="${OUT:-inventory/hosts.yml}"

server_pub=$(terraform -chdir="$TF_DIR" output -raw server_public_ip)
server_priv=$(terraform -chdir="$TF_DIR" output -raw server_private_ip)
worker_pub=$(terraform -chdir="$TF_DIR" output -json worker_public_ips)
worker_priv=$(terraform -chdir="$TF_DIR" output -json worker_private_ips)

{
  echo "# AUTO-GENERATED by generate-inventory.sh — do not edit by hand."
  echo "all:"
  echo "  children:"
  echo "    server:"
  echo "      hosts:"
  echo "        \"${server_pub}\":"
  echo "          public_ip: \"${server_pub}\""
  echo "          private_ip: \"${server_priv}\""
  echo "    agents:"
  echo "      hosts:"
  paste <(jq -r '.[]' <<<"$worker_pub") <(jq -r '.[]' <<<"$worker_priv") \
    | while IFS=$'\t' read -r pub priv; do
        echo "        \"${pub}\":"
        echo "          public_ip: \"${pub}\""
        echo "          private_ip: \"${priv}\""
      done
  echo "    k3s_cluster:"
  echo "      children:"
  echo "        server:"
  echo "        agents:"
} >"$OUT"

echo "Wrote $OUT"
